on:
  workflow_dispatch:

jobs:

  call-workflow-passing-data:
    uses: ananta-verse/re-usable-workflow/.github/workflows/my-action.yml@main
    with:
      word-to-print: ${{ vars.DEVOPS_LEARNER }}

    # secrets: inherit
    secrets:
      envPat: ${{ secrets.ENVPAT }}

  reusable-output-printer:
    needs: call-workflow-passing-data
    runs-on: ubuntu-latest
    steps:
      - name: Print Reusable return value.
        run: echo "${{ needs.call-workflow-passing-data.outputs.resuable-return }}
