on:
  workflow_dispatch:

jobs:

  call-workflow-passing-data:
    uses: ananta-verse/re-usable-workflow/.github/workflows/my-action.yml@v1.0.1
    with:
      word-to-print: ${{ vars.DEVOPS_LEARNER }}

    # secrets: inherit
    secrets:
      envPat: ${{ secrets.envPAT }}
